### ISSUE TITLE
allow configuration of task variables

### ISSUE THREAD

**Issue by mkyc** [lechuckroh/task-intellij-plugin#3]
Hi, amazing plugin!

I'd like to run task with variables i.e., 

```shell
task mytask SOME_VARIABLE=some-value
```

**Comment by lechuckroh** [comment]
@mkyc No problem!!

**Comment by lechuckroh** [comment]
@mkyc You can download updated version from https://github.com/lechuckroh/task-intellij-plugin/releases/tag/v1.3.0 before publicly available

**Comment by mkyc** [comment]
@lechuckroh it does work with [environment variables syntax](https://taskfile.dev/#/usage?id=environment-variables) ❤️ 

```yaml
version: '3'

env:
  TEST: test

tasks:
  print:
    desc: echo TEST env
    cmds:
      - echo TEST=$TEST
```

![Screenshot 2022-01-15 at 22 07 11](https://user-images.githubusercontent.com/28505782/149637729-04f767b0-9e08-4103-aa53-cc94063204f2.png)

```
task --taskfile /lalala/Taskfile.yml print
TEST=test2
task: [print] echo TEST=$TEST

Process finished with exit code 0
```


It does not work with [variables syntax](https://taskfile.dev/#/usage?id=variables) though. 

```yaml
version: '3'

vars:
  TEST: test

tasks:
  print:
    desc: echo TEST env
    cmds:
      - echo TEST={{.TEST}}
```

![Screenshot 2022-01-15 at 22 07 11](https://user-images.githubusercontent.com/28505782/149637729-04f767b0-9e08-4103-aa53-cc94063204f2.png)


```
task --taskfile /lalala/Taskfile.yml print
TEST=test
task: [print] echo TEST=test

Process finished with exit code 0
```

That solves my issue for sure, but I guess variables syntax would be nice to have as well. 

Great job!

**Comment by lechuckroh** [comment]
@mkyc 

In my environment (Mac + zsh), variables syntax works as expected.

```
task --taskfile /lalala/Taskfile.yml print
TEST=test2
task: [print] echo TEST=test2

Process finished with exit code 0
```

> Since some shells don’t support above syntax to set environment variables (Windows) tasks also accepts a similar style when not in the beginning of the command.

It seems your shell doesn't support environment variables. 😢 

I'll reopen this issue and working on your case..

Thank you for your reporting. 👍

**Comment by mkyc** [comment]
@lechuckroh that is interesting. 

With code

```yaml
version: '3'

vars:
  TEST: test

tasks:
  print:
    desc: echo TEST env
    cmds:
      - echo TEST={{.TEST}}
```

I get directly in shell:

```shell
➜  p git:(mkyc/b1) ✗ TEST=test2 task print
task: [print] echo TEST=test
TEST=test
➜  p git:(mkyc/b1) ✗ task print TEST=test2
task: [print] echo TEST=test2
TEST=test2
➜  p git:(mkyc/b1) ✗ echo $SHELL
/bin/zsh

```

**Comment by lechuckroh** [comment]
@mkyc Oops!! sorry.. I omitted `vars:` block in my `Taskfile.yml`.

Now I got the same output with you.. 😃

**Comment by lechuckroh** [comment]
@mkyc 
You can download v1.3.1 from https://github.com/lechuckroh/task-intellij-plugin/releases/tag/v1.3.1

```
task --taskfile /foo/Taskfile.yml print TEST=\"test2\" "TEST2=\"foo bar\""
version: '3'

vars:
  TEST: test

tasks:
  print:
    cmds:
      - cat Taskfile.yml
      - echo TEST={{.TEST}} TEST2={{.TEST2}}
TEST=test2 TEST2=foo bar
task: [print] cat Taskfile.yml
task: [print] echo TEST="test2" TEST2="foo bar"

Process finished with exit code 0
```

Now it works as expected!!

**Comment by mkyc** [comment]
Works perfectly right now 👍 

With code: 

```yaml
version: '3'

env:
  TEST1: test

vars:
  TEST2: test

tasks:
  print:
    desc: echo TEST env
    cmds:
      - echo TEST1=$TEST1
      - echo TEST2={{.TEST2}}
```

and configuration:

<img width="230" alt="Screenshot 2022-01-16 at 15 22 55" src="https://user-images.githubusercontent.com/28505782/149663956-086520ca-86eb-4618-b7af-eda6689354c6.png">

I get output as expected:

```
task --taskfile /lalala/Taskfile.yml print TEST2=\"test2\"
task: [print] echo TEST1=$TEST1
task: [print] echo TEST2="test2"
TEST1=test1
TEST2=test2

Process finished with exit code 0
```

So from that perspective all looks cool, thank you!

Two more suggestions but rather UI related:
1. if that is possible then window to edit variables same as environment variables would be nice. 
2. I would move "Variables" input under "Variables" label same as you did with environment variables. 

<img width="464" alt="Screenshot 2022-01-16 at 15 26 35" src="https://user-images.githubusercontent.com/28505782/149664098-d698c0da-8315-4a48-8565-69f979256c87.png">

Anyways great job!
